"""NEXUS Trust Engine - Cross-language test vectors.

These test vectors define inputs and EXACT expected outputs that MUST produce
identical results in C, Python, and TypeScript implementations of the INCREMENTS
trust algorithm.

Golden reference values were generated by running each vector through the Python
IncrementTrustEngine and recording exact numerical results.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class GoldenReference:
    """Exact expected output from running a test vector through the engine."""

    final_score: float
    final_level: int


@dataclass
class TrustVectorSpec:
    """Specification for a cross-language trust engine test vector.

    Each vector defines a sequence of events and the exact expected outputs.
    Events are (event_type, value) tuples where:
      - ("GOOD", quality): good event with given quality (0.0-1.0+)
      - ("BAD", severity): bad event with given severity (0.0-1.0)
      - ("IDLE", 0): idle tick (decay window with neutral event)
    """

    name: str
    events: list[tuple[str, float]]
    golden: GoldenReference
    note: str = ""
    subsystem: str = "default"


def run_vector(
    events: list[tuple[str, float]],
    subsystem: str = "default",
) -> tuple[float, int]:
    """Execute events through the Python TrustEngine.

    Returns (final_score, final_level).
    Call from within the jetson/ package (pythonpath includes jetson/).
    """
    from trust.increments import IncrementTrustEngine, TrustEvent

    engine = IncrementTrustEngine()
    engine.register_subsystem(subsystem)

    for event_type, value in events:
        if event_type == "GOOD":
            evt = TrustEvent.good("heartbeat_ok", value, subsystem=subsystem)
        elif event_type == "BAD":
            evt = TrustEvent.bad("reflex_error", value, subsystem=subsystem)
        elif event_type == "IDLE":
            evt = TrustEvent(
                "system_boot",
                quality=0.0,
                severity=0.0,
                timestamp=0.0,
                subsystem=subsystem,
                is_bad=False,
            )
        else:
            raise ValueError(f"Unknown event type: {event_type}")

        engine.evaluate_window(subsystem, [evt])

    return engine.get_trust_score(subsystem), engine.get_autonomy_level(subsystem)


def run_vector_detailed(
    events: list[tuple[str, float]],
    subsystem: str = "default",
) -> dict:
    """Execute events and return detailed results including intermediates."""
    from trust.increments import IncrementTrustEngine, TrustEvent

    engine = IncrementTrustEngine()
    engine.register_subsystem(subsystem)

    intermediate_scores: list[float] = []
    intermediate_levels: list[int] = []

    for event_type, value in events:
        if event_type == "GOOD":
            evt = TrustEvent.good("heartbeat_ok", value, subsystem=subsystem)
        elif event_type == "BAD":
            evt = TrustEvent.bad("reflex_error", value, subsystem=subsystem)
        elif event_type == "IDLE":
            evt = TrustEvent(
                "system_boot",
                quality=0.0,
                severity=0.0,
                timestamp=0.0,
                subsystem=subsystem,
                is_bad=False,
            )
        else:
            raise ValueError(f"Unknown event type: {event_type}")

        engine.evaluate_window(subsystem, [evt])
        intermediate_scores.append(engine.get_trust_score(subsystem))
        intermediate_levels.append(engine.get_autonomy_level(subsystem))

    return {
        "final_score": engine.get_trust_score(subsystem),
        "final_level": engine.get_autonomy_level(subsystem),
        "intermediate_scores": intermediate_scores,
        "intermediate_levels": intermediate_levels,
    }


# ===================================================================
# Golden reference test vectors
# ===================================================================
# All values below were generated by running run_vector() against the
# Python IncrementTrustEngine with default TrustParams.
#
# Engine parameters:
#   alpha_gain = 0.002, alpha_loss = 0.05, alpha_decay = 0.0001
#   t_floor = 0.2, quality_cap = 10, streak_bonus = 0.00005
#   severity_exponent = 1.0, n_penalty_slope = 0.1
#   promotion_cooldown_hours = 72.0
#
# Formula (Branch 1 - Gain):
#   delta = alpha_gain * (1 - prev_trust) * avg_quality * (min(n_good, 10) / 10)
#         + streak_bonus * min(consecutive_clean, 24)
#
# Formula (Branch 2 - Penalty):
#   delta = -alpha_loss * prev_trust * (max_severity ** exp) * n_penalty
#   where n_penalty = 1 + 0.1 * (n_bad - 1)
#
# Formula (Branch 3 - Decay):
#   delta = -alpha_decay * (prev_trust - t_floor)
# ===================================================================

TRUST_TEST_VECTORS: list[TrustVectorSpec] = [
    TrustVectorSpec(
        name="empty_start",
        events=[],
        golden=GoldenReference(
            final_score=0.0,
            final_level=0,
        ),
        note="No events processed. Trust remains at 0.0, level L0.",
    ),
    TrustVectorSpec(
        name="ten_good_events",
        events=[("GOOD", 1.0)] * 10,
        golden=GoldenReference(
            final_score=0.0042470014,
            final_level=0,
        ),
        note="10 consecutive quality-1.0 good events. Score ~0.004, still L0.",
    ),
    TrustVectorSpec(
        name="one_bad_event",
        events=[("GOOD", 1.0)] * 25 + [("BAD", 1.0)],
        golden=GoldenReference(
            final_score=0.2,
            final_level=0,
        ),
        note=(
            "25 good events build trust to ~0.020. "
            "One severity-1.0 bad event: penalty = -0.05 * 0.020 * 1.0 = -0.001, "
            "drops to ~0.019, but penalty branch floor-clamps to 0.2."
        ),
    ),
    TrustVectorSpec(
        name="path_to_L1",
        events=[("GOOD", 1.0)] * 60,
        golden=GoldenReference(
            final_score=0.0686595284,
            final_level=0,
        ),
        note=(
            "60 quality-1.0 good events -> score ~0.069. "
            "Still L0 because L1 requires trust >= 0.20."
        ),
    ),
    TrustVectorSpec(
        name="path_to_L3",
        events=[("GOOD", 1.0)] * 200,
        golden=GoldenReference(
            final_score=0.2600640335,
            final_level=1,
        ),
        note=(
            "200 quality-1.0 good events -> score ~0.260, reaches L1 "
            "(trust >= 0.20, obs >= 8h, clean >= 4). "
            "L2 blocked by promotion_cooldown (72h)."
        ),
    ),
    TrustVectorSpec(
        name="consecutive_bad_escalation",
        events=[("GOOD", 1.0)] * 500 + [("BAD", 1.0)] * 5,
        golden=GoldenReference(
            final_score=0.5049736474,
            final_level=0,
        ),
        note=(
            "500 good events -> trust ~0.653, L1. "
            "5 consecutive severity-1.0 bad events cause trust loss: "
            "delta proportional to current trust, so magnitude decreases "
            "as trust drops. Total loss ~0.148 over 5 windows. "
            "Bad events demote from L1 to L0."
        ),
    ),
    TrustVectorSpec(
        name="idle_decay",
        events=[("GOOD", 1.0)] * 300 + [("IDLE", 0.0)] * 100,
        golden=GoldenReference(
            final_score=0.3916111018,
            final_level=1,
        ),
        note=(
            "300 good events -> trust ~0.394. "
            "100 idle ticks cause very slow decay: "
            "delta per idle = -0.0001 * (trust - 0.2), ~0.00194 total decay."
        ),
    ),
    TrustVectorSpec(
        name="mixed_severity",
        events=[
            ("GOOD", 1.0),
            ("GOOD", 1.0),
            ("GOOD", 2.0),
            ("BAD", 1.0),
            ("GOOD", 1.0),
            ("GOOD", 3.0),
            ("GOOD", 1.0),
            ("GOOD", 1.0),
        ],
        golden=GoldenReference(
            final_score=0.2012595761,
            final_level=1,
        ),
        note=(
            "Mixed severity: 3 good (quality 1,1,2), 1 bad (sev 1), "
            "then 4 more good (1,3,1,1). Bad event floor-clamps to 0.2. "
            "Subsequent good events barely move above floor. Final level=1 "
            "because observation hours >= 8h and clean windows >= 4."
        ),
    ),
]

# Convenience: name-to-vector lookup
TEST_VECTOR_MAP: dict[str, TrustVectorSpec] = {v.name: v for v in TRUST_TEST_VECTORS}


def regenerate_golden_references() -> dict[str, tuple[float, int]]:
    """Regenerate all golden references by running vectors through the engine.

    Use this when the engine algorithm changes to update the golden references.
    Returns a dict mapping vector name to (final_score, final_level).
    """
    results: dict[str, tuple[float, int]] = {}
    for vector in TRUST_TEST_VECTORS:
        score, level = run_vector(vector.events, vector.subsystem)
        results[vector.name] = (score, level)
    return results
