"""
Runtime monitoring framework for NEXUS.

Processes events against configurable rules, tracks alerts,
and computes monitor health metrics.
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional


@dataclass
class MonitorEvent:
    """An event to be processed by the runtime monitor."""

    timestamp: float
    source: str
    event_type: str
    value: Any = None
    metadata: Optional[Dict[str, Any]] = None


@dataclass
class MonitorRule:
    """A rule that can be triggered by monitor events."""

    name: str
    condition_fn: Callable[[MonitorEvent], bool]
    threshold: float = 0.0
    severity: str = "warning"  # "info", "warning", "error", "critical"
    cooldown: float = 0.0  # minimum seconds between triggers


@dataclass
class Alert:
    """An active alert generated by a triggered rule."""

    alert_id: str
    rule_name: str
    severity: str
    timestamp: float
    event: MonitorEvent
    acknowledged: bool = False


class RuntimeMonitor:
    """Processes events and manages rule-based alerting."""

    def __init__(self) -> None:
        self._rules: Dict[str, MonitorRule] = {}
        self._active_alerts: List[Alert] = []
        self._last_trigger: Dict[str, float] = {}
        self._event_history: List[MonitorEvent] = []
        self._trigger_counts: Dict[str, int] = {}

    def add_rule(self, rule: MonitorRule) -> None:
        """Register a monitoring rule."""
        self._rules[rule.name] = rule
        if rule.name not in self._trigger_counts:
            self._trigger_counts[rule.name] = 0

    def process_event(self, event: MonitorEvent) -> List[Alert]:
        """Process a single event against all rules. Returns triggered alerts."""
        self._event_history.append(event)
        triggered: List[Alert] = []
        now = time.time()
        for name, rule in self._rules.items():
            if not self.evaluate_condition(event, rule):
                continue
            # Check cooldown
            last = self._last_trigger.get(name, 0.0)
            if (now - last) < rule.cooldown:
                continue
            alert = Alert(
                alert_id=str(uuid.uuid4()),
                rule_name=name,
                severity=rule.severity,
                timestamp=now,
                event=event,
            )
            self._active_alerts.append(alert)
            self._last_trigger[name] = now
            self._trigger_counts[name] = self._trigger_counts.get(name, 0) + 1
            triggered.append(alert)
        return triggered

    def evaluate_condition(self, event: MonitorEvent, rule: MonitorRule) -> bool:
        """Evaluate a single rule condition against an event."""
        try:
            return rule.condition_fn(event)
        except Exception:
            return False

    def compute_trigger_frequency(self, rule: str, time_window: float = 60.0) -> float:
        """Compute how often a rule has triggered within a time window.

        Args:
            rule: Name of the rule.
            time_window: Window in seconds (default 60).

        Returns:
            Triggers per second within the window.
        """
        if time_window <= 0:
            return 0.0
        count = self._trigger_counts.get(rule, 0)
        return count / time_window

    def get_active_alerts(self) -> List[Alert]:
        """Return all currently active (non-acknowledged) alerts."""
        return [a for a in self._active_alerts if not a.acknowledged]

    def acknowledge_alert(self, alert_id: str) -> bool:
        """Acknowledge an alert by ID. Returns True if found and acknowledged."""
        for alert in self._active_alerts:
            if alert.alert_id == alert_id:
                alert.acknowledged = True
                return True
        return False

    def compute_monitor_health(self) -> float:
        """Compute an overall health score for the monitor (0.0-100.0).

        Higher is healthier. Deductions for active unacknowledged alerts,
        with severity weighting.
        """
        health = 100.0
        severity_penalty = {
            "info": 0.5,
            "warning": 2.0,
            "error": 5.0,
            "critical": 10.0,
        }
        for alert in self._active_alerts:
            if not alert.acknowledged:
                penalty = severity_penalty.get(alert.severity, 2.0)
                health -= penalty
        return max(min(health, 100.0), 0.0)
